In [1]:
import numpy as np
import sys

# The Basics

In [15]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [13]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


In [5]:
#Get Dimension
a.ndim

1

In [6]:
#Get Shape
a.shape

(3,)

In [7]:
b.shape

(2, 3)

In [9]:
#Get Type 
a.dtype

dtype('int32')

In [10]:
#Get size
a.itemsize

4

In [12]:
#Get Total Size
a.nbytes

12

In [14]:
b.itemsize

8

## Accessing / Changing specific elements, row, columns

In [18]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [21]:
#Get element
a[1, 5]

13

In [22]:
#Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
#Get specific column
a[:, 2]

array([ 3, 10])

In [24]:
#Getting fancier[startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [26]:
a[1,5] = 20
print(a)

a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [32]:
#3d example
b = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [33]:
#Get specific element(work outside in)
b[0, 1, 1]

4

In [34]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

## Initializing Different types of arrays

In [39]:
#All 0s matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [40]:
#All ones matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [42]:
#Any number
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [44]:
# Any other number (full-like)
np.full_like(a.shape, 4)

array([4, 4])

In [49]:
# Random decimal numbers
np.random.rand(4,2,3)

array([[[0.78975658, 0.36146643, 0.85613684],
        [0.20228225, 0.1573033 , 0.43794432]],

       [[0.28705214, 0.21934984, 0.42406062],
        [0.21817197, 0.15415387, 0.36073406]],

       [[0.29723216, 0.25889225, 0.99604252],
        [0.55248376, 0.27066335, 0.80219932]],

       [[0.59708434, 0.78160004, 0.03472627],
        [0.8885163 , 0.91140198, 0.3263728 ]]])

In [77]:
#Random integers
np.random.randint(-4,7, size=(3,3))

array([[ 1,  3,  3],
       [-3,  0,  6],
       [ 1,  2,  2]])

In [79]:
#The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [87]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful when copying arrays

In [91]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


# Mathematics

In [92]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [93]:
a+2

array([3, 4, 5, 6])

In [94]:
a*2

array([2, 4, 6, 8])

In [96]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [99]:
a+=2
a

array([ 7,  8,  9, 10])

In [100]:
b = np.array([1,0,1,0])
a + b

array([ 8,  8, 10, 10])

In [102]:
a * b

array([7, 0, 9, 0])

In [104]:
a ** 2

array([ 49,  64,  81, 100], dtype=int32)

In [105]:
#Take a sin
np.sin(a)

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [107]:
#Look up scipy routines for more mathematics

# Linear Algebra

In [111]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [110]:
b = np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [112]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [114]:
c = np.identity(3)
np.linalg.det(c)

1.0

In [ ]:
# https://numpy.org/doc/stable/reference/routines.linalg.html

## Statistics

In [115]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [121]:
np.min(stats)

1

In [123]:
np.max(stats, axis=0)

array([4, 5, 6])

In [124]:
np.sum(stats)

21

# Reorganizing Arrays

In [7]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
#Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [10]:
#Horizontal stack
np.hstack((v1,v2))

array([1, 2, 3, 4, 5, 6, 7, 8])

## Load Data from file

In [21]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


#### Boolean Masking and Advanced Indexing

In [18]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [19]:
#You can index with list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])

a[[1,2,8]]

array([2, 3, 9])

In [24]:
np.any(filedata>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [26]:
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

## Save and Load Arrays

In [3]:
x = np.arange(0,10,1)
y = x**2
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [4]:
np.savez("x_y-squared.npz", x_axis= x, y_axis=y)

In [5]:
del x,y

In [6]:
%whos

Variable   Type      Data/Info
------------------------------
np         module    <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
sys        module    <module 'sys' (built-in)>


In [7]:
load_xy = np.load("x_y-squared.npz")
print(load_xy.files)

['x_axis', 'y_axis']


In [9]:
%whos

Variable   Type       Data/Info
-------------------------------
load_xy    NpzFile    <numpy.lib.npyio.NpzFile <...>object at 0x7ff61de077c0>
np         module     <module 'numpy' from '/ho<...>kages/numpy/__init__.py'>
sys        module     <module 'sys' (built-in)>


In [10]:
x = load_xy["x_axis"]
y = load_xy["y_axis"]
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  4  9 16 25 36 49 64 81]


In [11]:
array_out = np.block([x[:, np.newaxis], y[:, np.newaxis]])
print("the output array has shape ", array_out.shape, " with values: ")
print(array_out)

the output array has shape  (10, 2)  with values: 
[[ 0  0]
 [ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]
 [ 6 36]
 [ 7 49]
 [ 8 64]
 [ 9 81]]


In [12]:
np.savetxt("x_y-squared.csv", X = array_out, header="x, y", delimiter=",")

In [13]:
del x,y

In [14]:
load_xy = np.loadtxt("x_y-squared.csv", delimiter=",")

In [15]:
load_xy.shape

(10, 2)

In [16]:
x = load_xy[:, 0]
y = load_xy[:, 1]
print(x)
print(y)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[ 0.  1.  4.  9. 16. 25. 36. 49. 64. 81.]
